version: '3.2'

services: 
    flaskassignment:
        build:
            context: ./
        ports:
            - 5000:5000
    
    db:
        image: mysql
        # ports: 
        #     - 3306: 3306
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=user
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=flaskdb